[package]
name = "sxiaum-block"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
sxiaum-types = { workspace = true }
sxiaum-crypto = { path = "../crypto" }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
sha2.workspace = true
ed25519-dalek.workspace = true
bincode = { workspace = true }

[dev-dependencies]

