use crate::error::HeaderError;
use anyhow::Result;
use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::time::{SystemTime, UNIX_EPOCH};
use sxiaum_types::{serde_sig, Address, BlockHeight, Canonical, Hash, Timestamp};

/// Canonical block header representing the consensus and state commitment for a single block.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct BlockHeader {
    /// 32-byte cryptographic hash of the immediate parent block header.
    pub parent_hash: Hash,
    /// Commitment root of the state database after applying all transactions in this block.
    pub state_root: Hash,
    /// Merkle root of all transactions contained in the block body.
    pub tx_root: Hash,
    /// Merkle root of all transaction receipts generated by executing the block body.
    pub receipts_root: Hash,
    /// Merkle root commitment to the active validator set authorized for this block.
    pub validator_root: Hash,
    /// Optional ZK-STARK / Groth16 validity proof verifying the state transition.
    pub zk_proof: Option<Vec<u8>>,
    /// Monotonically increasing height of this block in the chain.
    pub height: BlockHeight,
    /// Unix timestamp (seconds since epoch) when the block was proposed.
    pub timestamp: Timestamp,
    /// Address of the validator who proposed and signed this block.
    pub proposer: Address,
    /// Randomness beacon seed derived from VRF / threshold randomness.
    pub randomness_beacon: Hash,
    /// Block header format version for hard forks and protocol upgrades.
    #[serde(default = "default_block_version")]
    pub version: u32,
    /// Maximum gas allowed in this block. Must not exceed [`crate::MAX_BLOCK_GAS_LIMIT`].
    #[serde(default = "default_gas_limit")]
    pub gas_limit: u64,
    /// Actual gas consumed by all transactions in this block.
    #[serde(default)]
    pub gas_used: u64,
    /// Consensus-specific extra data (e.g. round metadata, proposer seal).
    /// Limited to [`crate::MAX_EXTRA_DATA_SIZE`] bytes.
    #[serde(default)]
    pub extra_data: Vec<u8>,
    /// Replay-protection chain identifier. Must match [`sxiaum_types::SXIAUM_CHAIN_ID`] on mainnet.
    #[serde(default = "default_chain_id")]
    pub chain_id: u64,
    /// Proposer's 64-byte Ed25519 signature over the canonical unsigned header hash.
    #[serde(default, with = "serde_sig")]
    pub signature: Option<[u8; 64]>,
}

fn default_block_version() -> u32 {
    crate::BLOCK_VERSION_CURRENT
}

fn default_gas_limit() -> u64 {
    crate::DEFAULT_BLOCK_GAS_LIMIT
}

fn default_chain_id() -> u64 {
    sxiaum_types::SXIAUM_CHAIN_ID
}

#[derive(Serialize)]
struct UnsignedBlockHeaderRef<'a> {
    parent_hash: Hash,
    state_root: Hash,
    tx_root: Hash,
    receipts_root: Hash,
    validator_root: Hash,
    zk_proof: Option<&'a [u8]>,
    height: BlockHeight,
    timestamp: Timestamp,
    proposer: Address,
    randomness_beacon: Hash,
    version: u32,
    gas_limit: u64,
    gas_used: u64,
    extra_data: &'a [u8],
    chain_id: u64,
    #[serde(with = "serde_sig")]
    signature: Option<[u8; 64]>,
}

impl<'a> UnsignedBlockHeaderRef<'a> {
    fn try_encode(&self) -> Result<Vec<u8>> {
        use bincode::Options;
        let options = bincode::options()
            .with_little_endian()
            .with_varint_encoding()
            .reject_trailing_bytes();

        options
            .serialize(self)
            .map_err(|e| anyhow::anyhow!("serialize unsigned header error: {}", e))
    }
}

impl BlockHeader {
    /// Create a new block header for a specific height and parent with default mainnet parameters.
    pub fn new(parent_hash: Hash, height: BlockHeight) -> Self {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        Self {
            parent_hash,
            state_root: [0u8; 32],
            tx_root: [0u8; 32],
            receipts_root: [0u8; 32],
            validator_root: [0u8; 32],
            zk_proof: None,
            height,
            timestamp: ts,
            proposer: Address::zero(),
            randomness_beacon: [0u8; 32],
            version: crate::BLOCK_VERSION_CURRENT,
            gas_limit: crate::DEFAULT_BLOCK_GAS_LIMIT,
            gas_used: 0,
            extra_data: Vec::new(),
            chain_id: sxiaum_types::SXIAUM_CHAIN_ID,
            signature: None,
        }
    }

    /// Create the canonical genesis block header (height 0).
    pub fn genesis() -> Self {
        Self {
            parent_hash: [0u8; 32],
            state_root: [0u8; 32],
            tx_root: [0u8; 32],
            receipts_root: [0u8; 32],
            validator_root: [0u8; 32],
            zk_proof: None,
            height: 0,
            timestamp: crate::GENESIS_TIMESTAMP,
            proposer: Address::zero(),
            randomness_beacon: [0u8; 32],
            version: crate::BLOCK_VERSION_CURRENT,
            gas_limit: crate::DEFAULT_BLOCK_GAS_LIMIT,
            gas_used: 0,
            extra_data: Vec::new(),
            chain_id: sxiaum_types::SXIAUM_CHAIN_ID,
            signature: None,
        }
    }

    /// Calculate the canonical 32-byte SHA-256 hash of the header.
    ///
    /// The hash is computed deterministically over the header fields with `signature`
    /// set to `None`, ensuring signatures sign the exact preimage and remain verifiable.
    pub fn try_hash(&self) -> Result<Hash> {
        let unsigned_view = UnsignedBlockHeaderRef {
            parent_hash: self.parent_hash,
            state_root: self.state_root,
            tx_root: self.tx_root,
            receipts_root: self.receipts_root,
            validator_root: self.validator_root,
            zk_proof: self.zk_proof.as_deref(),
            height: self.height,
            timestamp: self.timestamp,
            proposer: self.proposer,
            randomness_beacon: self.randomness_beacon,
            version: self.version,
            gas_limit: self.gas_limit,
            gas_used: self.gas_used,
            extra_data: self.extra_data.as_slice(),
            chain_id: self.chain_id,
            signature: None,
        };
        let bytes = unsigned_view.try_encode()?;
        let mut hasher = Sha256::new();
        hasher.update(&bytes);
        let result = hasher.finalize();
        let mut out = [0u8; 32];
        out.copy_from_slice(&result);
        Ok(out)
    }

    #[cfg(test)]
    pub fn hash(&self) -> Hash {
        self.try_hash().expect("header hashing should not fail")
    }

    /// Serialize the header into its canonical deterministic binary format.
    pub fn try_encode(&self) -> Result<Vec<u8>> {
        <Self as Canonical>::try_encode(self)
    }

    /// Deserialize a header from its canonical binary format.
    pub fn decode(bytes: &[u8]) -> Result<Self> {
        <Self as Canonical>::decode(bytes)
    }

    /// Return the canonical binary size of the header in bytes.
    pub fn size_bytes(&self) -> Result<usize> {
        self.try_encode().map(|b| b.len())
    }

    /// Verify that the header correctly links to its expected parent hash.
    #[must_use]
    pub fn verify_parent(&self, expected_parent_hash: Hash) -> bool {
        self.parent_hash == expected_parent_hash
    }

    /// Verify that the block height strictly matches the expected height.
    #[must_use]
    pub fn verify_height(&self, expected_height: BlockHeight) -> bool {
        self.height == expected_height
    }

    /// Verify that the timestamp is strictly greater than the previous block's timestamp.
    #[must_use]
    pub fn verify_timestamp(&self, previous_timestamp: Timestamp) -> bool {
        self.timestamp > previous_timestamp
    }

    /// Sign the block header as the proposer using an Ed25519 signing key.
    ///
    /// Automatically populates the header's `proposer` address if it is currently zero.
    pub fn sign(&mut self, signing_key: &SigningKey) -> Result<()> {
        let derived_proposer = Address::from_public_key(&signing_key.verifying_key().to_bytes());
        if self.proposer.is_zero() {
            self.proposer = derived_proposer;
        } else if self.proposer != derived_proposer {
            return Err(HeaderError::ProposerKeyMismatch {
                expected: self.proposer,
                derived: derived_proposer,
            }
            .into());
        }

        let hash = self.try_hash()?;
        let sig = signing_key.sign(&hash);
        self.signature = Some(sig.to_bytes());
        Ok(())
    }

    /// Sign the block header using an abstract signer (in-memory or remote HSM).
    ///
    /// Automatically populates the header's `proposer` address if currently zero.
    pub fn sign_with_signer<S: sxiaum_crypto::Signer + ?Sized>(
        &mut self,
        signer: &S,
    ) -> Result<()> {
        let pubkey = signer.public_key();
        let derived_proposer = Address::from_public_key(&pubkey.to_bytes());
        if self.proposer.is_zero() {
            self.proposer = derived_proposer;
        } else if self.proposer != derived_proposer {
            return Err(HeaderError::ProposerKeyMismatch {
                expected: self.proposer,
                derived: derived_proposer,
            }
            .into());
        }

        let hash = self.try_hash()?;
        let sig = signer.sign(&hash)?;
        self.signature = Some(sig.to_bytes());
        Ok(())
    }

    /// Verify the proposer's Ed25519 signature on the header with strict malleability checks.
    pub fn verify_signature(&self, public_key_bytes: &[u8; 32]) -> Result<bool> {
        let sig_bytes = self
            .signature
            .ok_or_else(|| HeaderError::MissingSignature)?;

        let derived_proposer = Address::from_public_key(public_key_bytes);
        if derived_proposer != self.proposer {
            return Err(HeaderError::ProposerKeyMismatch {
                expected: self.proposer,
                derived: derived_proposer,
            }
            .into());
        }

        let public_key = VerifyingKey::from_bytes(public_key_bytes)
            .map_err(|e| HeaderError::InvalidPublicKey(e.to_string()))?;

        let sig = Signature::from_bytes(&sig_bytes);

        public_key
            .verify_strict(&self.try_hash()?, &sig)
            .map(|_| true)
            .map_err(|e| HeaderError::SignatureVerificationFailed(format!("{:?}", e)).into())
    }

    // --- Field Setters ---

    pub fn set_state_root(&mut self, root: Hash) {
        self.state_root = root;
    }

    pub fn set_tx_root(&mut self, root: Hash) {
        self.tx_root = root;
    }

    pub fn set_receipts_root(&mut self, root: Hash) {
        self.receipts_root = root;
    }

    pub fn set_validator_root(&mut self, root: Hash) {
        self.validator_root = root;
    }

    pub fn set_randomness_beacon(&mut self, beacon: Hash) {
        self.randomness_beacon = beacon;
    }

    pub fn set_zk_proof(&mut self, proof: Vec<u8>) {
        self.zk_proof = Some(proof);
    }

    pub fn set_timestamp(&mut self, ts: Timestamp) {
        self.timestamp = ts;
    }

    pub fn set_proposer(&mut self, proposer: Address) {
        self.proposer = proposer;
    }

    pub fn set_version(&mut self, version: u32) {
        self.version = version;
    }

    pub fn set_gas_limit(&mut self, gas_limit: u64) {
        self.gas_limit = gas_limit;
    }

    pub fn set_gas_used(&mut self, gas_used: u64) {
        self.gas_used = gas_used;
    }

    pub fn set_extra_data(&mut self, data: Vec<u8>) {
        self.extra_data = data;
    }

    pub fn set_chain_id(&mut self, chain_id: u64) {
        self.chain_id = chain_id;
    }

    // --- Validation Methods ---

    /// Perform basic structural and size checks on the header fields.
    pub fn validate_basic(&self) -> Result<()> {
        if self.timestamp == 0 {
            return Err(HeaderError::ZeroTimestamp.into());
        }

        if self.height == 0 && self.parent_hash != [0u8; 32] {
            return Err(HeaderError::GenesisParentNonZero.into());
        }

        if self.extra_data.len() > crate::MAX_EXTRA_DATA_SIZE {
            return Err(HeaderError::ExtraDataTooLarge {
                size: self.extra_data.len(),
                max: crate::MAX_EXTRA_DATA_SIZE,
            }
            .into());
        }

        if let Some(proof) = &self.zk_proof {
            if proof.len() > crate::MAX_ZK_PROOF_SIZE {
                return Err(HeaderError::ZkProofTooLarge {
                    size: proof.len(),
                    max: crate::MAX_ZK_PROOF_SIZE,
                }
                .into());
            }
        }

        Ok(())
    }

    /// Perform comprehensive mainnet validation on the header.
    ///
    /// Validates:
    /// * Basic structural limits
    /// * Canonical protocol version
    /// * Replay protection chain identifier
    /// * Gas limit bounded between [`crate::MIN_BLOCK_GAS_LIMIT`] and [`crate::MAX_BLOCK_GAS_LIMIT`]
    /// * Gas used does not exceed gas limit
    /// * Non-genesis blocks require non-zero proposer
    /// * Timestamp does not drift beyond [`crate::MAX_FUTURE_BLOCK_TIME_SECS`]
    /// * Timestamp is at or after [`crate::GENESIS_TIMESTAMP`]
    pub fn validate_mainnet(&self, local_time: Timestamp) -> Result<()> {
        self.validate_basic()?;

        if self.version != crate::BLOCK_VERSION_CURRENT {
            return Err(HeaderError::InvalidVersion {
                expected: crate::BLOCK_VERSION_CURRENT,
                actual: self.version,
            }
            .into());
        }

        if self.chain_id != sxiaum_types::SXIAUM_CHAIN_ID {
            return Err(HeaderError::InvalidChainId {
                expected: sxiaum_types::SXIAUM_CHAIN_ID,
                actual: self.chain_id,
            }
            .into());
        }

        if self.gas_limit > crate::MAX_BLOCK_GAS_LIMIT {
            return Err(HeaderError::GasLimitExceeded {
                gas_limit: self.gas_limit,
                max: crate::MAX_BLOCK_GAS_LIMIT,
            }
            .into());
        }

        if self.gas_limit < crate::MIN_BLOCK_GAS_LIMIT {
            return Err(HeaderError::GasLimitTooLow {
                gas_limit: self.gas_limit,
                min: crate::MIN_BLOCK_GAS_LIMIT,
            }
            .into());
        }

        if self.gas_used > self.gas_limit {
            return Err(HeaderError::GasUsedExceedsLimit {
                gas_used: self.gas_used,
                gas_limit: self.gas_limit,
            }
            .into());
        }

        if self.height > 0 {
            if self.parent_hash == [0u8; 32] {
                return Err(HeaderError::NonGenesisParentZero {
                    height: self.height,
                }
                .into());
            }
            if self.proposer.is_zero() {
                return Err(HeaderError::NonGenesisZeroProposer.into());
            }
        } else if !self.proposer.is_zero() {
            return Err(HeaderError::GenesisNonZeroProposer.into());
        }

        if self.timestamp < crate::GENESIS_TIMESTAMP {
            return Err(HeaderError::TimestampBeforeGenesis {
                timestamp: self.timestamp,
                genesis_time: crate::GENESIS_TIMESTAMP,
            }
            .into());
        }

        let max_allowed_time = local_time.saturating_add(crate::MAX_FUTURE_BLOCK_TIME_SECS);
        if self.timestamp > max_allowed_time {
            return Err(HeaderError::FutureTimestamp {
                timestamp: self.timestamp,
                local_time,
                max_drift: crate::MAX_FUTURE_BLOCK_TIME_SECS,
            }
            .into());
        }

        Ok(())
    }

    /// Perform pairwise validation between a child header and its verified parent header.
    pub fn validate_parent_child(&self, parent: &BlockHeader, local_time: Timestamp) -> Result<()> {
        self.validate_mainnet(local_time)?;

        let parent_hash = parent.try_hash()?;
        if !self.verify_parent(parent_hash) {
            return Err(HeaderError::ParentHashMismatch {
                expected: hex::encode(parent_hash),
                actual: hex::encode(self.parent_hash),
            }
            .into());
        }

        let expected_height = parent
            .height
            .checked_add(1)
            .ok_or(HeaderError::HeightOverflow {
                height: parent.height,
            })?;

        if !self.verify_height(expected_height) {
            return Err(HeaderError::HeightMismatch {
                expected: expected_height,
                actual: self.height,
            }
            .into());
        }

        if self.timestamp <= parent.timestamp {
            return Err(HeaderError::TimestampRegression {
                child_time: self.timestamp,
                parent_time: parent.timestamp,
            }
            .into());
        }

        Ok(())
    }
}

impl sxiaum_crypto::hash::Hashable for BlockHeader {
    fn try_hash(&self) -> Result<sxiaum_crypto::hash::Hash, anyhow::Error> {
        self.try_hash()
    }
}

#[cfg(test)]
mod tests {
    use super::BlockHeader;
    use ed25519_dalek::SigningKey;
    use sxiaum_types::Address;

    #[test]
    fn new_header_initializes_expected_defaults() {
        let parent_hash = [1u8; 32];
        let header = BlockHeader::new(parent_hash, 7);

        assert_eq!(header.parent_hash, parent_hash);
        assert_eq!(header.height, 7);
        assert_eq!(header.state_root, [0u8; 32]);
        assert_eq!(header.tx_root, [0u8; 32]);
        assert_eq!(header.receipts_root, [0u8; 32]);
        assert_eq!(header.validator_root, [0u8; 32]);
        assert_eq!(header.proposer, Address::zero());
        assert_eq!(header.signature, None);
        assert!(header.timestamp > 0);
        assert_eq!(header.version, crate::BLOCK_VERSION_CURRENT);
        assert_eq!(header.gas_limit, crate::DEFAULT_BLOCK_GAS_LIMIT);
        assert_eq!(header.gas_used, 0);
        assert!(header.extra_data.is_empty());
        assert_eq!(header.chain_id, sxiaum_types::SXIAUM_CHAIN_ID);
    }

    #[test]
    fn genesis_header_is_fixed_and_valid() {
        let header = BlockHeader::genesis();

        assert_eq!(header.parent_hash, [0u8; 32]);
        assert_eq!(header.height, 0);
        assert_eq!(header.timestamp, crate::GENESIS_TIMESTAMP);
        assert_eq!(header.version, crate::BLOCK_VERSION_CURRENT);
        assert_eq!(header.chain_id, sxiaum_types::SXIAUM_CHAIN_ID);
        header
            .validate_basic()
            .expect("genesis header should validate basic");
        header
            .validate_mainnet(crate::GENESIS_TIMESTAMP)
            .expect("genesis header should validate mainnet");
    }

    #[test]
    fn hash_ignores_signature_and_encode_round_trips() {
        let mut header = BlockHeader::new([2u8; 32], 3);
        header.proposer = Address([3u8; 32]);

        let unsigned_hash = header.try_hash().unwrap();
        let encoded = header.try_encode().unwrap();
        let decoded = BlockHeader::decode(&encoded).expect("decode should succeed");

        header.signature = Some([9u8; 64]);

        assert_eq!(
            decoded,
            BlockHeader::decode(&encoded).expect("repeat decode should succeed")
        );
        assert_eq!(unsigned_hash, header.try_hash().unwrap());
        assert_eq!(header.hash(), unsigned_hash);
    }

    #[test]
    fn parent_height_timestamp_and_root_setters_work() {
        let mut header = BlockHeader::new([4u8; 32], 5);

        header.set_state_root([5u8; 32]);
        header.set_tx_root([6u8; 32]);
        header.set_receipts_root([7u8; 32]);
        header.set_validator_root([8u8; 32]);
        header.set_randomness_beacon([9u8; 32]);
        header.set_timestamp(42);

        assert!(header.verify_parent([4u8; 32]));
        assert!(header.verify_height(5));
        assert!(header.verify_timestamp(41));
        assert_eq!(header.state_root, [5u8; 32]);
        assert_eq!(header.tx_root, [6u8; 32]);
        assert_eq!(header.receipts_root, [7u8; 32]);
        assert_eq!(header.validator_root, [8u8; 32]);
        assert_eq!(header.randomness_beacon, [9u8; 32]);
        assert_eq!(header.timestamp, 42);
        assert!(header.size_bytes().unwrap() > 0);
    }

    #[test]
    fn signing_and_signature_verification_work() {
        let signing_key = SigningKey::from_bytes(&[10u8; 32]);
        let public_key = signing_key.verifying_key().to_bytes();
        let proposer = Address::from_public_key(&public_key);
        let mut header = BlockHeader::new([11u8; 32], 9);
        header.proposer = proposer;

        header.sign(&signing_key).expect("signing should succeed");

        assert!(header
            .verify_signature(&public_key)
            .expect("verification should succeed"));
    }

    #[test]
    fn signing_auto_populates_zero_proposer() {
        let signing_key = SigningKey::from_bytes(&[10u8; 32]);
        let public_key = signing_key.verifying_key().to_bytes();
        let proposer = Address::from_public_key(&public_key);
        let mut header = BlockHeader::new([11u8; 32], 9);

        assert!(header.proposer.is_zero());
        header.sign(&signing_key).expect("signing should succeed");
        assert_eq!(header.proposer, proposer);
        assert!(header.verify_signature(&public_key).unwrap());
    }

    #[test]
    fn verification_rejects_mismatched_proposer_key() {
        let signing_key = SigningKey::from_bytes(&[12u8; 32]);
        let other_public_key = SigningKey::from_bytes(&[13u8; 32])
            .verifying_key()
            .to_bytes();
        let mut header = BlockHeader::new([14u8; 32], 10);
        header.proposer = Address::from_public_key(&signing_key.verifying_key().to_bytes());
        header.sign(&signing_key).expect("signing should succeed");

        assert!(header.verify_signature(&other_public_key).is_err());
    }

    #[test]
    fn entropy_changes_hash_and_serializes() {
        let mut header1 = BlockHeader::new([2u8; 32], 3);
        let mut header2 = header1.clone();

        header1.randomness_beacon = [1u8; 32];
        header2.randomness_beacon = [2u8; 32];

        assert_ne!(header1.try_hash().unwrap(), header2.try_hash().unwrap());

        let bytes = bincode::serialize(&header1).unwrap();
        let decoded: BlockHeader = bincode::deserialize(&bytes).unwrap();
        assert_eq!(header1.randomness_beacon, decoded.randomness_beacon);
        assert_eq!(header1.try_hash().unwrap(), decoded.try_hash().unwrap());
    }

    #[test]
    fn new_field_setters_update_values() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.set_version(2);
        header.set_gas_limit(8_000_000);
        header.set_gas_used(5_000_000);
        header.set_extra_data(vec![0xAA, 0xBB]);
        header.set_chain_id(999);
        header.set_proposer(Address([7u8; 32]));

        assert_eq!(header.version, 2);
        assert_eq!(header.gas_limit, 8_000_000);
        assert_eq!(header.gas_used, 5_000_000);
        assert_eq!(header.extra_data, vec![0xAA, 0xBB]);
        assert_eq!(header.chain_id, 999);
        assert_eq!(header.proposer, Address([7u8; 32]));
    }

    #[test]
    fn validate_basic_rejects_oversized_extra_data() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.set_extra_data(vec![0u8; crate::MAX_EXTRA_DATA_SIZE + 1]);
        assert!(header.validate_basic().is_err());
    }

    #[test]
    fn validate_basic_rejects_oversized_zk_proof() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.set_zk_proof(vec![0u8; crate::MAX_ZK_PROOF_SIZE + 1]);
        assert!(header.validate_basic().is_err());
    }

    #[test]
    fn validate_basic_accepts_valid_zk_proof() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.set_zk_proof(vec![0u8; 1024]);
        assert!(header.validate_basic().is_ok());
    }

    #[test]
    fn validate_mainnet_accepts_valid_header() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        header.set_timestamp(now);
        header
            .validate_mainnet(now)
            .expect("valid header should pass mainnet validation");
    }

    #[test]
    fn validate_mainnet_rejects_wrong_version() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        header.set_version(99);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_wrong_chain_id() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        header.set_chain_id(1);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_gas_limit_exceeding_max() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        header.set_gas_limit(crate::MAX_BLOCK_GAS_LIMIT + 1);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_gas_limit_too_low() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        header.set_gas_limit(crate::MIN_BLOCK_GAS_LIMIT - 1);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_gas_used_exceeding_limit() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        header.set_gas_limit(1_000_000);
        header.set_gas_used(2_000_000);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_zero_proposer_for_non_genesis() {
        let header = BlockHeader::new([1u8; 32], 1);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_future_timestamp() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        header.set_timestamp(now + crate::MAX_FUTURE_BLOCK_TIME_SECS + 10);
        assert!(header.validate_mainnet(now).is_err());
    }

    #[test]
    fn validate_mainnet_rejects_timestamp_before_genesis() {
        let mut header = BlockHeader::new([1u8; 32], 1);
        header.proposer = Address([1u8; 32]);
        header.set_timestamp(crate::GENESIS_TIMESTAMP - 1);
        assert!(header.validate_mainnet(crate::GENESIS_TIMESTAMP).is_err());
    }

    #[test]
    fn validate_mainnet_accepts_genesis_with_zero_proposer() {
        let header = BlockHeader::genesis();
        header
            .validate_mainnet(header.timestamp)
            .expect("genesis should pass mainnet validation");
    }

    #[test]
    fn validate_parent_child_enforces_linkage_and_sequence() {
        let parent = BlockHeader::genesis();
        let parent_hash = parent.try_hash().unwrap();
        let mut child = BlockHeader::new(parent_hash, 1);
        child.proposer = Address([2u8; 32]);
        child.set_timestamp(parent.timestamp + 2);

        child
            .validate_parent_child(&parent, child.timestamp)
            .expect("valid parent-child linkage should pass");

        // Wrong parent hash
        let mut bad_child = child.clone();
        bad_child.parent_hash = [99u8; 32];
        assert!(bad_child
            .validate_parent_child(&parent, child.timestamp)
            .is_err());

        // Wrong height
        let mut bad_height_child = child.clone();
        bad_height_child.height = 2;
        assert!(bad_height_child
            .validate_parent_child(&parent, child.timestamp)
            .is_err());

        // Regressing timestamp
        let mut bad_time_child = child.clone();
        bad_time_child.set_timestamp(parent.timestamp);
        assert!(bad_time_child
            .validate_parent_child(&parent, child.timestamp)
            .is_err());
    }
}
